CREATE TABLE carros (
    id BIGSERIAL PRIMARY KEY,
    placa VARCHAR(7) NOT NULL UNIQUE,
    modelo VARCHAR(100) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    ano INT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL'
);